<a href="https://colab.research.google.com/github/lanchandres/Trabajo-Final-Econometria/blob/main/TrabajoFinalEconometria.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Bases de datos y librerias

In [ ]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import os

servicios_basicos_por_vivienda = pd.read_excel('06_2022_CPV_Servicios_basicos_vivienda.xlsx', sheet_name='1.1')
educacion = pd.read_excel('2022_CPV_Educacion.xlsx', sheet_name='3.1')
trabajo = pd.read_excel('2022_CPV_Trabajo.xlsx', sheet_name='9.1')
tamaño_hogar = pd.read_excel('01_2022_CPV_CONDICIONES_DE_VIDA.xlsx', sheet_name='1.1')
densidad_poblacional = pd.read_excel('01_2022_CPV_Estructura_poblacional.xlsx', sheet_name='4.1')

Base de datos de servicios basicos por vivienda

In [ ]:
servicios_basicos_por_vivienda = servicios_basicos_por_vivienda.drop(servicios_basicos_por_vivienda.columns[0], axis=1)
servicios_basicos_por_vivienda = servicios_basicos_por_vivienda.drop(servicios_basicos_por_vivienda.index[0:12])
servicios_basicos_por_vivienda.columns = ['provincia', 'canton', 'area de residencia',
                                          'Agua por red pública', 'Recolección de basura', 'Red pública de alcantarillado', 'Energía eléctrica de red pública'
]
servicios_basicos_por_vivienda = servicios_basicos_por_vivienda.drop(servicios_basicos_por_vivienda.index[-5:])
servicios_basicos_por_vivienda = servicios_basicos_por_vivienda[~servicios_basicos_por_vivienda['canton'].str.contains('total', case=False, na=False)]
servicios_basicos_por_vivienda = servicios_basicos_por_vivienda[~servicios_basicos_por_vivienda['area de residencia'].str.contains('total', case=False, na=False)]
servicios_basicos_por_vivienda = servicios_basicos_por_vivienda[~servicios_basicos_por_vivienda['provincia'].str.contains('total', case=False, na=False)]
servicios_basicos_por_vivienda

,provincia,canton,area de residencia,Agua por red pública,Recolección de basura,Red pública de alcantarillado,Energía eléctrica de red pública
17,Azuay,Cuenca,Urbana,113652,113497,111248,113566
18,Azuay,Cuenca,Rural,61067,60268,35659,64924
20,Azuay,Girón,Urbana,1291,1262,1239,1291
21,Azuay,Girón,Rural,2146,1383,503,2403
23,Azuay,Gualaceo,Urbana,4075,4008,3639,4075
...,...,...,...,...,...,...,...
741,Santa Elena,Santa Elena,Rural,28411,30712,6133,29901
743,Santa Elena,La Libertad,Urbana,28169,29027,21396,28662
744,Santa Elena,La Libertad,Rural,15,9,NaN,14
746,Santa Elena,Salinas,Urbana,8293,8691,7775,8529
747,Santa Elena,Salinas,Rural,12255,13008,8161,12755

Base de datos de Educación

In [ ]:
educacion = educacion.drop(educacion.columns[0], axis=1)
educacion = educacion.drop(educacion.index[0:10])
educacion.columns = ['provincia', 'canton', 'area de residencia', 'asistencia a un establecimiento de enseñanza', 'Total de personas', 'Ninguno', 'Centro de Desarrollo Infantil/Creciendo con nuestros hijos/Guardería',
                     '0 años', '1 año', '2 años', 'Número total de personas que asisten o asistieron a educación inicial',
                     '0 años', '1-2 modulos', '3-4 modulos', '5-6 modulos','Número total de personas que asisten o asistieron a alfabetizacion',
                     '0 años', '1 año preparatoria', 'De a 2 a 4 años Básica Elemental', 'De 5 a 7 años Básica Media', 'De 8 a 10 años Básica Superior','Número total de personas que asisten o asistieron a Educación General Básica',
                     '0 años', '1 año', '2 años', '3 años','Número total de personas que asisten o asistieron a Bachillerato',
                     '0 años', '1 año', '2 años', 'Número total de personas que asisten o asistieron a ciclo Postbachillerato',
                     '0 años', '1 a 2 años ETTS', '3 años o mas ETTS','Número total de personas que asisten o asistieron a Educación Técnica o Tecnológica',
                     '0 años', '1 a 3 años ESEP', '4 años o mas ESEP','Número total de personas que asisten o asistieron a Educación Superior',
                     '0 años', '1 a 3 años', '4 a 5 años','Número total de personas que asisten o asistieron a Maestría/Posgrado',
                     '0 años', '1 a 3 años', '4 a 5 años','Número total de personas que asisten o asistieron a PHD/Doctorado']
educacion = educacion.drop(educacion.index[-2:])
educacion = educacion[~educacion['canton'].str.contains('total', case=False, na=False)]
educacion = educacion[~educacion['asistencia a un establecimiento de enseñanza'].str.contains('total', case=False, na=False)]
educacion = educacion[~educacion['area de residencia'].str.contains('total', case=False, na=False)]

educacion

,provincia,canton,area de residencia,asistencia a un establecimiento de enseñanza,Total de personas,Ninguno,Centro de Desarrollo Infantil/Creciendo con nuestros hijos/Guardería,0 años,1 año,2 años,...,4 años o mas ESEP,Número total de personas que asisten o asistieron a Educación Superior,0 años,1 a 3 años,4 a 5 años,Número total de personas que asisten o asistieron a Maestría/Posgrado,0 años,1 a 3 años,4 a 5 años,Número total de personas que asisten o asistieron a PHD/Doctorado
10,Total Nacional,Nacional,Nacional,Nacional,16938986,1249373,236575,117413,219592,5817,...,1853166,2809268,2723,271124,65282,339129,173,12053,13770,25996
14,Total Nacional,Nacional,Urbana,Asiste,3477710,NaN,105314,66480,130771,NaN,...,296489,755797,1608,4643,342,6593,88,341,121,550
15,Total Nacional,Nacional,Urbana,No asiste,7209441,657702,18339,6041,8254,2928,...,1176147,1441427,515,215201,51902,267618,49,9641,10922,20612
17,Total Nacional,Nacional,Rural,Asiste,2014938,NaN,95081,40598,74170,NaN,...,81215,251478,494,1223,110,1827,29,104,35,168
18,Total Nacional,Nacional,Rural,No asiste,4236897,591671,17841,4294,6397,2889,...,299315,360566,106,50057,12928,63091,7,1967,2692,4666
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2166,Santa Elena,La Libertad,Rural,No asiste,53,7,NaN,NaN,1,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2171,Santa Elena,Salinas,Urbana,Asiste,10703,NaN,595,210,395,NaN,...,453,1657,5,13,5,23,NaN,0,1,1
2172,Santa Elena,Salinas,Urbana,No asiste,24363,1973,211,21,36,9,...,2926,3727,3,495,176,674,NaN,29,41,70
2174,Santa Elena,Salinas,Rural,Asiste,18975,NaN,1551,378,823,NaN,...,470,2049,3,16,0,19,NaN,NaN,NaN,NaN
2175,Santa Elena,Salinas,Rural,No asiste,32760,3042,279,26,51,22,...,2583,3301,1,360,181,542,NaN,26,32,58

Base de datos Trabajo

In [ ]:
trabajo = trabajo.drop(trabajo.columns[0], axis=1)
trabajo = trabajo.drop(trabajo.index[0:14])
trabajo.columns = ['provincia', 'canton', 'sexo al nacer', 'nivel de instrucción',
                   'Número total de personas de 15 años o más', 'Ocupado', 'Descupado', 'Fuera de la fuerza de trabajo']
trabajo = trabajo.drop(trabajo.index[-3:])
trabajo = trabajo[~trabajo['nivel de instrucción'].str.contains('total', case=False, na=False)]
trabajo = trabajo[~trabajo['sexo al nacer'].str.contains('total', case=False, na=False)]
trabajo = trabajo[~trabajo['provincia'].str.contains('total', case=False, na=False)]
trabajo

,provincia,canton,sexo al nacer,nivel de instrucción,Número total de personas de 15 años o más,Ocupado,Descupado,Fuera de la fuerza de trabajo
50,Azuay,Total Azuay,Hombres,Ninguno,5910,1983,236,3691
51,Azuay,Total Azuay,Hombres,Centro de Desarrollo Infantil/Creciendo con nu...,22,10,NaN,12
52,Azuay,Total Azuay,Hombres,Educación inicial/Preescolar/SAFPI,109,43,3,63
53,Azuay,Total Azuay,Hombres,Alfabetización (EBJA),759,384,27,348
54,Azuay,Total Azuay,Hombres,Educación General Básica,84873,57029,4018,23826
...,...,...,...,...,...,...,...,...
8261,Santa Elena,Salinas,Mujeres,Ciclo Postbachillerato,215,76,18,121
8262,Santa Elena,Salinas,Mujeres,Educación Técnica o Tecnológica Superior (inst...,554,325,46,183
8263,Santa Elena,Salinas,Mujeres,"Educación Superior (universidades, escuelas po...",5790,2703,772,2315
8264,Santa Elena,Salinas,Mujeres,Maestría/Posgrado,690,618,18,54
8265,Santa Elena,Salinas,Mujeres,PHD/Doctorado,63,51,1,11

Base de Datos Tamaño hogar

In [ ]:
tamaño_hogar= tamaño_hogar.drop(tamaño_hogar.columns[0], axis=1)
tamaño_hogar = tamaño_hogar.drop(tamaño_hogar.index[0:12])
tamaño_hogar.columns = ['Provincia', 'cantón', 'área de residencia', 'sexo del representante del hogar' ,
                        'Número total de hogares','Hogares con 0 cuartos','1 persona por cuarto o menos',
                        'Más de 1 y hasta 3 personas por cuarto','Más de 3 y hasta 5 personas por cuarto'
                        ,'Más de 5 personas por cuarto']
tamaño_hogar = tamaño_hogar[~tamaño_hogar['cantón'].str.contains('total', case=False, na=False)]
tamaño_hogar = tamaño_hogar[~tamaño_hogar['área de residencia'].str.contains('total', case=False, na=False)]
tamaño_hogar = tamaño_hogar[~tamaño_hogar['sexo del representante del hogar'].str.contains('total', case=False, na=False)]

tamaño_hogar

,Provincia,cantón,área de residencia,sexo del representante del hogar,Número total de hogares,Hogares con 0 cuartos,1 persona por cuarto o menos,Más de 1 y hasta 3 personas por cuarto,Más de 3 y hasta 5 personas por cuarto,Más de 5 personas por cuarto
14,Total Nacional,Nacional,Urbana,Hombres,1960303,81889,716204,1035430,108655,18125
15,Total Nacional,Nacional,Urbana,Mujeres,1339366,68111,565107,611284,80177,14687
17,Total Nacional,Nacional,Rural,Hombres,1233038,59842,378883,684474,92658,17181
18,Total Nacional,Nacional,Rural,Mujeres,656120,37059,253578,315869,42102,7512
30,Azuay,Cuenca,Urbana,Hombres,71290,1037,34011,34602,1468,172
...,...,...,...,...,...,...,...,...,...,...
2166,Santa Elena,La Libertad,Rural,Mujeres,12,4,NaN,8,NaN,NaN
2171,Santa Elena,Salinas,Urbana,Hombres,6892,333,2015,3430,919,195
2172,Santa Elena,Salinas,Urbana,Mujeres,3129,177,1225,1350,318,59
2174,Santa Elena,Salinas,Rural,Hombres,8953,574,2112,4926,1092,249
2175,Santa Elena,Salinas,Rural,Mujeres,5421,437,1363,2855,646,120

Base de datos densidad_poblacional

In [ ]:
densidad_poblacional = densidad_poblacional.drop(densidad_poblacional.columns[0], axis=1)
densidad_poblacional = densidad_poblacional.drop(densidad_poblacional.index[0:12])
densidad_poblacional.columns = [ 'Provincia','canton de residencia' , 'Poblacion' , 'Área(km2)',
                        'Densidad poblacional (personas por km2)']
densidad_poblacional = densidad_poblacional.drop(densidad_poblacional.index[-2:])
densidad_poblacional = densidad_poblacional[~densidad_poblacional['canton'].str.contains('total', case=False, na=False)]


densidad_poblacional

,Provincia,canton de residencia,Poblacion,Área(km2),Densidad poblacional (personas por km2)
12,Azuay,Gualaceo,43188,346.14,124.770324
13,Azuay,Nabón,14776,631.55,23.396406
14,Azuay,Paute,26782,267.88,99.977602
15,Azuay,Pucará,9693,638.75,15.174951
16,Azuay,San Fernando,3738,143.14,26.114294
...,...,...,...,...,...
226,Santo Domingo De Los Tsáchilas,Santo Domingo,441583,3455.3,127.798744
227,Santo Domingo De Los Tsáchilas,La Concordia,51386,324.33,158.437394
228,Santa Elena,Santa Elena,186687,3595.4,51.923847
229,Santa Elena,La Libertad,112247,25.28,4440.150316
230,Santa Elena,Salinas,86801,67.78,1280.628504

# Modelo y Variables

¿Cómo influyen las características socioeconómicas y geográficas del hogar en el acceso a servicios básicos en Ecuador?

# Preparacion y Transformacion de Datos

# Estimacion del Modelo

# Verficacion

# Resultados y Discusiones

# Conclusiones

# Bibliografia